import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container } style={{backgroundColor:'pink'}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>

      <main className={styles.main}>
        <h1 className="title">
          Read{' '}
          <Link href="/Posts/first-post">
            <a>Post page</a>
          </Link>
        </h1>
      </main >

      <footer className={styles.footer}>
      </footer>
    </div >
  )
}
